apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydevops
  labels:
    app: mydevops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydevops
  template:
    metadata:
      labels:
        app: mydevops
    spec:
      containers:
        - name: mydevops
          image: harshalsable1/ethans123
          ports:
            - containerPort: 80
